### ISSUE TITLE
Create .github/workflows directory

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#1]
## Summary
- Create a new .github directory to hold workflows and MD templates in the future
- Inside workflows place a simple yml file(it doesn't required to work or do something for this moment)

**Comment by joanne-cmd** [comment]
I’d like to resolve this. i have a good background in devsecops

**Comment by 0xdevcollins** [comment]
Can I jump on this task?

**Comment by JosueBrenes** [comment]
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.

# Proposed Solution for Issue

I would resolve this issue in the following way:

1. **Create the .github Directory**: Start by creating a new directory named `.github` in the root of the repository.

2. **Add the Workflows Subdirectory**: Inside the `.github` directory, create another folder named `workflows`. This folder will serve as the location for all workflow YAML files and MD templates in the future.

3. **Create a Placeholder YAML File**: Inside the `workflows` directory, add a simple YAML file (e.g., `placeholder.yml`). This file doesn't need to contain any operational code for now; it will act as a placeholder. An example content for the YAML file could be:

   ```yaml
   name: Placeholder Workflow
   on:
     push:
       branches:
         - main
   jobs:
     placeholder_job:
       runs-on: ubuntu-latest
       steps:
         - name: Placeholder Step
           run: echo "This is a placeholder workflow file."
   ```

4. **Commit and Push**: After creating the `.github/workflows/placeholder.yml` file structure, commit and push the changes to the repository. This setup will establish the necessary directory structure for future workflows and templates.
