### ISSUE TITLE
Add view details for the product

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#20]
# 📘 Issue Description
**Add a Detailed Product View Modal**

We want to provide users with a way to view more in-depth details about a product directly from the product card. This feature will enhance the browsing experience by displaying additional product information in a modal. For now, placeholder data will be used.

**Task Details:**
1. **Button Design**: 
   - Add a **"View Details"** button to each product card.
   - Place the button in a prominent but non-intrusive location within the card.

2. **Modal Design**: 
   - Clicking the button should open a modal displaying detailed product information.
   - Include placeholder sections in the modal for:
     - Product Title
     - Description
     - Price
     - Ratings/Reviews (optional)
     - Larger product images or image carousel.

3. **Styling and Responsiveness**:
   - Ensure the modal design aligns with the marketplace’s overall theme.
   - Make the modal responsive for different devices and screen sizes.

4. **User Experience**:
   - Add a clear **"Close"** button or icon to dismiss the modal.
   - Ensure the modal opens smoothly and does not disrupt the user experience.

**Comment by RolandoDrRobot** [comment]
Can I take this one please?

**Comment by PedroCo3lho** [comment]
Hello @danielcdz,
I’m a full-stack developer with experience working with Next.js and TailwindCSS. The to-do task seems clear to me, and I’d love to contribute to the project, hope to be assigned

**Comment by qgatssdev** [comment]
I'm a fullstack engineer with years of experience. I can get this done in less than 3 days if assigned to me.

**Comment by khayss** [comment]
## Background and Relevant Experience

I have experience building intuitive and responsive UIs with TypeScript and Next.js. I’ve worked on enhancing user interactions through modals and detailed product views, ensuring a smooth browsing experience.

## Plan for Tackling the Issue

1. Add a "View Details" button to each product card.
2. On click, open a modal with placeholders for product title, description, price, ratings, and images.
3. Ensure the modal matches the existing theme and is responsive.

**Comment by starknetbrother** [comment]
GM GM!  I’m a frontend developer excited to join in as a new contributor—looking forward to collaborating! 

Adding a Detailed Product View Modal
Button Design
I’ll add a "View Details" button to each product card, ensuring it’s easy to spot but doesn’t clutter the design.

Modal Design
Clicking the button will open a modal. The modal will include placeholder sections for:

Product Title
Description
Price
Ratings/Reviews (optional)
Larger product images or an image carousel
Styling & Responsiveness
The modal will match the current theme and be fully responsive for both desktop and mobile.

User Experience
I’ll include a clear "Close" button and ensure smooth transitions to make it feel natural.

**Comment by KevinLatino** [comment]
Hello @danielcdz! My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I will add a "View Details" button to each product card. Clicking the button will open a modal displaying product details such as title, description, price, ratings/reviews, and a larger image or carousel. I’ll probably implement this using useParams to filter by the product ID, ensuring the correct details are shown for each product. I will be careful with the responsive design

I think I can finish this in 5 hours

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
May I handle this issue?I can comfortably handle this issues

**Comment by JosueBrenes** [comment]
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member.⛩️

I estimate this will take 1 day to complete.

## How I Would Resolve This

To implement the feature of a detailed product view modal, I would follow these steps:

---

### 1. **Button Design**
   - Add a "View Details" button to each product card.
   - Placement:
     - Place the button at the bottom or near the center of the card, ensuring it is visible but does not overwhelm the design.
   - Styling:
     - Use a subtle yet clickable style with hover effects to make it interactive.
       ```css
       .view-details-btn {
         background-color: #007bff; /* Example primary color */
         color: white;
         border: none;
         padding: 10px 15px;
         border-radius: 5px;
         cursor: pointer;
       }
       .view-details-btn:hover {
         background-color: #0056b3;
       }
       ```

---

### 2. **Modal Design**
   - Use a library (e.g., React Modal, Bootstrap Modal) or custom HTML/CSS to create the modal.
   - Structure:
     - **Title**: Display the product name prominently.
     - **Description**: Include placeholder text for the product description.
     - **Price**: Show the product price in bold.
     - **Ratings/Reviews (Optional)**: Add placeholder stars or text.
     - **Larger Product Images/Image Carousel**:
       - Add a single large image or integrate a carousel for multiple images.

   Example JSX for the Modal (React):
   ```jsx
   import React, { useState } from "react";

   function ProductCard({ product }) {
     const [showModal, setShowModal] = useState(false);

     const toggleModal = () => setShowModal(!showModal);

     return (
       <div className="product-card">
         <h3>{product.title}</h3>
         <button className="view-details-btn" onClick={toggleModal}>
           View Details
         </button>

         {showModal && (
           <div className="modal-overlay">
             <div className="modal-content">
               <button className="close-btn" onClick={toggleModal}>
                 ×
               </button>
               <h2>{product.title}</h2>
               <p>{product.description}</p>
               <p><strong>Price:</strong> ${product.price}</p>
               <div className="image-carousel">
                 <img src={product.image} alt={product.title} />
               </div>
               <div className="ratings">
                 <span>★★★★☆</span>
               </div>
             </div>
           </div>
         )}
       </div>
     );
   }
   ```

---

### 3. **Styling and Responsiveness**
   - Ensure the modal aligns with the marketplace's theme.
     ```css
     .modal-overlay {
       position: fixed;
       top: 0;
       left: 0;
       width: 100%;
       height: 100%;
       background-color: rgba(0, 0, 0, 0.5);
       display: flex;
       justify-content: center;
       align-items: center;
       z-index: 1000;
     }
     .modal-content {
       background: white;
       padding: 20px;
       border-radius: 10px;
       max-width: 500px;
       width: 90%;
       box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
     }
     .close-btn {
       background: transparent;
       border: none;
       font-size: 20px;
       position: absolute;
       top: 10px;
       right: 10px;
       cursor: pointer;
     }
     ```
   - Add media queries for responsiveness:
     ```css
     @media (max-width: 768px) {
       .modal-content {
         width: 95%;
         padding: 15px;
       }
     }
     ```

---

### 4. **User Experience**
   - Add a clear "Close" button or icon for dismissing the modal.
   - Ensure the modal opens with a smooth animation.
     ```css
     .modal-content {
       transform: scale(0.9);
       transition: transform 0.3s ease-in-out;
     }
     .modal-overlay.show .modal-content {
       transform: scale(1);
     }
     ```
   - Ensure accessibility (e.g., focus trapping within the modal, keyboard navigation support).

---

### 5. **Testing**
   - Test the button's functionality:
     - Ensure the "View Details" button triggers the modal correctly.
   - Validate modal content rendering:
     - Confirm all placeholder sections (title, description, price, etc.) display as intended.
   - Test responsiveness across devices:
     - Ensure the modal adapts to various screen sizes.
   - Verify smooth animations and transitions for a polished user experience.

---

### Deliverables:
   - Updated product card with "View Details" button.
   - A fully functional modal displaying placeholder product details.
   - Styled and responsive modal design.
   - Code tested for usability and cross-device compatibility.

---
